language: cpp

dist: bionic

compiler:
  - gcc

before_install:
  - sudo apt-get install -y libmicrohttpd-dev openssl

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && ./test/unit_tests ../test/resources

matrix:
  include:
	- compiler: gcc
	  addons:
		apt:
		  sources:
			- ubuntu-toolchain-r-test
		  packages:
			- g++-8
	  env:
		- CXX=g++-8

	- compiler: gcc
	  addons:
		apt:
		  sources:
			- ubuntu-toolchain-r-test
		  packages:
			- g++-9
	  env:
		- CXX=g++-9

	- compiler: clang
	  addons:
		apt:
		  sources:
			- ubuntu-toolchain-r-test
			- llvm-toolchain-bionic
		  packages:
			- clang-8
	  env:
		- CXX=clang++-8

	- compiler: clang
	  addons:
		apt:
		  sources:
			- ubuntu-toolchain-r-test
			- llvm-toolchain-bionic
		  packages:
			- clang-9
	  env:
		- CXX=clang++-9
