language: cpp

dist: bionic

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

before_install:
  - sudo apt-get install -y libmicrohttpd-dev openssl

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && ./test/unit_tests ../test/resources

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-8
      env:
        - CXX=g++-8
        - CC=gcc-8

    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-8
          packages:
            - clang-8
            - g++-8
      env:
        - CXX=clang++-8
        - CC=clang-8

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - g++-8
      env:
        - CXX=clang++-9
        - C=clang-9
